src/objects/AD_User__c.object
<CustomObject>
    <description>Active Directory Users</description>
    <label>AD User</label>
    <nameField>
        <displayFormat>AU-{00000}</displayFormat>
        <label>AD User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AD Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AD_Federation_Id__c</fullName>
        <label>AD Federation Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_First_Name__c</fullName>
        <label>AD First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Last_Name__c</fullName>
        <label>AD Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_User_Email__c</fullName>
        <label>AD User Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/AD_User_Inactivation__e.object
<CustomObject>
    <label>AD User Inactivation</label>
    <pluralLabel>AD User Inactivations</pluralLabel>
    <fields>
        <fullName>AD_Federation_Id__c</fullName>
        <label>AD Federation Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/ADUserTriggerHandler.cls
public class ADUserTriggerHandler {
    public static void updateADUser(List<AD_User__c> listOfADUsersIds){
        System.debug('200.01-##############ADUserTriggerHandler:processUpdate:List of AD Users to process: '+listOfADUsersIds);
        //Query all triggered Ad User records        
        List<AD_User__c> listOfADUsers = [SELECT Id, Name, CreatedDate, AD_Federation_Id__c, 
                                          AD_First_Name__c, AD_Last_Name__c, AD_User_Email__c, 
                                          Status__c FROM AD_User__c Where id IN :listOfADUsersIds];

        System.debug('202.01-##############ADUserTriggerHandler:processUpdate:FULL List of AD Users: '+listOfADUsers);
        List<AD_User_Inactivation__e> userEvents = new List<AD_User_Inactivation__e>();
        
        for (AD_User__c user : listOfADUsers) {
            userEvents.add(new AD_User_Inactivation__e(AD_Federation_Id__c=user.AD_Federation_Id__c, Status__c=user.Status__c));
        }
        System.debug('205.01-##############ADUserTriggerHandler:processUpdate:List of events to process: '+userEvents);
        // Call method to publish events
        List<Database.SaveResult> srs = EventBus.publish(userEvents);
        // Inspect publishing result
        for (Database.SaveResult sr: srs ) {
            if (sr.isSuccess()) {
                System.debug('210.01-##############ADUserTriggerHandler:processUpdate:Successfully published event: '+sr);
            } else {
                for(Database.Error err : sr.getErrors()) {
                    System.debug('Error returned: ' +
                                 err.getStatusCode() +
                                 ' - ' +
                                 err.getMessage());
                }
            }
        }
    }
}